// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Movie_Table_AddGenreIDColumn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movie_Table_AddGenreIDColumn));
        
        string IMigrationMetadata.Id
        {
            get { return "201809201433333_Movie_Table_AddGenreIDColumn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
